esphome:
  name: erlang

esp32:
  board: esp32dev
  framework:
    type: arduino
# Enable Home Assistant API
api:


ota:
  - platform: esphome
    password: "your_password"
logger:
  level: DEBUG
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

output:
  - platform: ledc
    pin: GPIO21
    id: output_red

  - platform: ledc
    pin: GPIO22
    id: output_green

  - platform: ledc
    pin: GPIO27
    id: output_blue

  - platform: ledc
    pin: GPIO26
    id: output_white

light:
  - platform: rgbw
    name: "RGB LED"
    red: output_red
    green: output_green
    blue: output_blue
    white: output_white
    restore_mode: ALWAYS_ON
